exports.up = function(knex) {
  return knex.schema
    .createTable('budgets', table => {
      table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
      table.uuid('user_id').references('id').inTable('users').onDelete('CASCADE')
      table.uuid('household_id').references('id').inTable('households').onDelete('CASCADE')
      table.string('name', 100).notNullable()
      table.text('description')
      table.decimal('total_income', 15, 2).defaultTo(0.00)
      table.decimal('total_expenses', 15, 2).defaultTo(0.00)
      table.date('start_date').notNullable()
      table.date('end_date')
      table.enum('period', ['weekly', 'monthly', 'quarterly', 'yearly', 'custom']).defaultTo('monthly')
      table.enum('status', ['draft', 'active', 'completed', 'archived']).defaultTo('draft')
      table.boolean('is_template').defaultTo(false)
      table.json('envelopes').defaultTo('[]') // JSON array of budget envelopes
      table.timestamps(true, true)
      
      table.index(['user_id'])
      table.index(['household_id'])
      table.index(['period'])
      table.index(['status'])
      table.index(['start_date'])
    })
    .createTable('budget_categories', table => {
      table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
      table.uuid('budget_id').references('id').inTable('budgets').onDelete('CASCADE')
      table.uuid('category_id').references('id').inTable('categories').onDelete('CASCADE')
      table.decimal('allocated_amount', 15, 2).notNullable()
      table.decimal('spent_amount', 15, 2).defaultTo(0.00)
      table.decimal('remaining_amount', 15, 2).defaultTo(0.00)
      table.enum('alert_threshold_type', ['percentage', 'fixed_amount'])
      table.decimal('alert_threshold_value', 15, 2)
      table.boolean('rollover_enabled').defaultTo(false)
      table.decimal('rollover_amount', 15, 2).defaultTo(0.00)
      table.timestamps(true, true)
      
      table.index(['budget_id'])
      table.index(['category_id'])
    })
    .createTable('goals', table => {
      table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
      table.uuid('user_id').references('id').inTable('users').onDelete('CASCADE')
      table.uuid('household_id').references('id').inTable('households').onDelete('CASCADE')
      table.string('name', 100).notNullable()
      table.text('description')
      table.enum('type', ['emergency_fund', 'vacation', 'house_down_payment', 'car', 'education', 'retirement', 'debt_payoff', 'custom']).notNullable()
      table.decimal('target_amount', 15, 2).notNullable()
      table.decimal('current_amount', 15, 2).defaultTo(0.00)
      table.decimal('target_monthly_contribution', 15, 2)
      table.date('target_date')
      table.date('start_date').defaultTo(knex.fn.now())
      table.enum('status', ['active', 'paused', 'completed', 'cancelled']).defaultTo('active')
      table.uuid('connected_account_id').references('id').inTable('accounts').onDelete('SET NULL')
      table.boolean('auto_transfer_enabled').defaultTo(false)
      table.decimal('auto_transfer_amount', 15, 2)
      table.enum('auto_transfer_frequency', ['weekly', 'monthly']).defaultTo('monthly')
      table.json('milestones').defaultTo('[]') // JSON array of milestone objects
      table.json('metadata').defaultTo('{}')
      table.timestamps(true, true)
      
      table.index(['user_id'])
      table.index(['household_id'])
      table.index(['type'])
      table.index(['status'])
      table.index(['target_date'])
    })
    .createTable('goal_contributions', table => {
      table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
      table.uuid('goal_id').references('id').inTable('goals').onDelete('CASCADE')
      table.uuid('transaction_id').references('id').inTable('transactions').onDelete('SET NULL')
      table.decimal('amount', 15, 2).notNullable()
      table.date('contribution_date').notNullable()
      table.text('notes')
      table.timestamps(true, true)
      
      table.index(['goal_id'])
      table.index(['transaction_id'])
      table.index(['contribution_date'])
    })
    .createTable('bills', table => {
      table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
      table.uuid('user_id').references('id').inTable('users').onDelete('CASCADE')
      table.uuid('household_id').references('id').inTable('households').onDelete('CASCADE')
      table.string('name', 100).notNullable()
      table.text('description')
      table.decimal('amount', 15, 2).notNullable()
      table.string('iso_currency_code', 3).defaultTo('USD')
      table.date('due_date').notNullable()
      table.enum('frequency', ['once', 'weekly', 'monthly', 'quarterly', 'yearly']).defaultTo('monthly')
      table.integer('frequency_interval').defaultTo(1)
      table.uuid('category_id').references('id').inTable('categories').onDelete('SET NULL')
      table.uuid('payee_account_id').references('id').inTable('accounts').onDelete('SET NULL')
      table.boolean('auto_pay_enabled').defaultTo(false)
      table.date('next_due_date').notNullable()
      table.date('last_paid_date')
      table.enum('status', ['active', 'paused', 'completed', 'cancelled']).defaultTo('active')
      table.boolean('is_recurring').defaultTo(true)
      table.json('reminder_settings').defaultTo('{}') // JSON object with reminder settings
      table.json('metadata').defaultTo('{}')
      table.timestamps(true, true)
      
      table.index(['user_id'])
      table.index(['household_id'])
      table.index(['category_id'])
      table.index(['due_date'])
      table.index(['next_due_date'])
      table.index(['status'])
    })
    .createTable('bill_payments', table => {
      table.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'))
      table.uuid('bill_id').references('id').inTable('bills').onDelete('CASCADE')
      table.uuid('transaction_id').references('id').inTable('transactions').onDelete('SET NULL)
      table.decimal('amount', 15, 2).notNullable()
      table.date('payment_date').notNullable()
      table.enum('status', ['pending', 'completed', 'failed', 'cancelled']).defaultTo('completed')
      table.text('notes')
      table.timestamps(true, true)
      
      table.index(['bill_id'])
      table.index(['transaction_id'])
      table.index(['payment_date'])
      table.index(['status'])
    })
}

exports.down = function(knex) {
  return knex.schema
    .dropTableIfExists('bill_payments')
    .dropTableIfExists('bills')
    .dropTableIfExists('goal_contributions')
    .dropTableIfExists('goals')
    .dropTableIfExists('budget_categories')
    .dropTableIfExists('budgets')
}